#just for tac
statistics=true
job=Master_SA
jobVersion=0.1
date=2026-03-22 232611914
contextName=Default
jobId=_2EP3wP3gEfCSuNPgWG1-bg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=SOUGUIETL
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=