#just for tac
statistics=true
job=Master_DWH
jobVersion=0.1
date=2026-03-22 154535113
contextName=Default
jobId=_HpbMcP3mEfCSuNPgWG1-bg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=SOUGUIETL
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=